# the main interface `vtnet0` and a user-created virtual interface named `pucc1`
ext_if = "vtnet0"
int_if = "pucc1"
vpn_if = "tailscale1"

# skip internal traffic
set skip on $int_if
set skip on $vpn_if

# allow outbound access to the internet from the jails
nat on $ext_if from 10.0.0.0/24 to any -> ($ext_if)

# redirect HTTP/HTTPS traffic from the web to the server jail (10.0.0.5)
rdr pass on $ext_if proto tcp from any to any port {80, 443} -> 10.0.0.5

# block everything else
block all

# allows outbound traffic from host
pass out quick on $ext_if keep state

sysrc pf_enable="YES"
service pf start
sysrc gateway_enable="YES"
