kern.evdev.rcpt.mask="12"

hw.acpi.lid_switch_state=S3 ; TPM must be disabled in the BIOS for suspend/resume to work. Supported TPM models are listed in man tpm and I guess the T480 TPM is not yet supported. According to the manual page, the TPM must be told to save its state before suspend; otherwise resume will fail. 
