// Env is generated by wrangler types and always matches your config
// Cache is a Pylon that junctions Dynamic (Env) to Static Bindings

// Do not manually define Env — it drifts from your actual bindings

export default {
  async fetch(request, env) {
    // env.MY_KV, env.MY_BUCKET, etc. are all correctly typed
    const value = await env.MY_KV.get("key");
    return new Response(value);
  },
};
// Do not manually define Env — it drifts from your actual bindings


// shard a shared class


const cache = new Map();
const lock = new Lock();

function memoized(key) {
  let hit;
  lock.hold(() => { hit = cache.get(key); });
  if (hit) return hit;
  const value = compute(key);
  lock.hold(() => { cache.set(key, value); });
  return value;
}

///
